# ifndef SAUVC2020_DEPTH_SENSOR_CONFIG_H
# define SAUVC2020_DEPTH_SENSOR_CONFIG_H

// Define competition regulation
# define QUALIFICATION_OPERATING_DEPTH float(0.6)
# define COMPETITION_OPERATING_DEPTH float(1.3)

// Define depth sensor config
# define OPERATING_DEPTH QUALIFICATION_OPERATING_DEPTH
# define DEPTH_TOLERANCE float(0.25)
# define DEPTH_SENSOR_MODEL MS5837::MS5837_02BA
# define FLUID_DENSITY 997

# endif //SAUVC2020_DEPTH_SENSOR_CONFIG_H
