# ifndef SAUVC2020_DEPTH_SENSOR_CONFIG_H
# define SAUVC2020_DEPTH_SENSOR_CONFIG_H
# define OPERATING_DEPTH float(213.9)
# define DEPTH_TOLERANCE float(3.25)

# endif //SAUVC2020_DEPTH_SENSOR_CONFIG_H
